<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[==server started==]]>
    </line>
    <line>
      <![CDATA[==database connected successfully==]]>
    </line>
    <line>
      <![CDATA[==Database closed successfully==]]>
    </line>
    <line>
      <![CDATA[==server closed successfully==]]>
    </line>
  </reporter-output>
  <suite started-at="2025-08-22T16:08:12 IST" name="Default suite" finished-at="2025-08-22T16:08:12 IST" duration-ms="91">
    <groups>
    </groups>
    <test started-at="2025-08-22T16:08:12 IST" name="Default test" finished-at="2025-08-22T16:08:12 IST" duration-ms="91">
      <class name="com.Ecommerce.Register.RegisterTest">
        <test-method is-config="true" signature="toConnectServer()[pri:0, instance:com.Ecommerce.Register.RegisterTest@55fe41ea]" started-at="2025-08-22T16:08:12 IST" name="toConnectServer" finished-at="2025-08-22T16:08:12 IST" duration-ms="15" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[==server started==]]>
            </line>
          </reporter-output>
        </test-method> <!-- toConnectServer -->
        <test-method is-config="true" signature="toConnectDatabase()[pri:0, instance:com.Ecommerce.Register.RegisterTest@55fe41ea]" started-at="2025-08-22T16:08:12 IST" name="toConnectDatabase" finished-at="2025-08-22T16:08:12 IST" duration-ms="2" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[==database connected successfully==]]>
            </line>
          </reporter-output>
        </test-method> <!-- toConnectDatabase -->
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.Ecommerce.Register.RegisterTest@55fe41ea]" started-at="2025-08-22T16:08:12 IST" name="setUp" finished-at="2025-08-22T16:08:12 IST" duration-ms="13" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.InvalidArgumentException">
            <message>
              <![CDATA[Data is Wrong.\src\main\resources\TestData\CommanData.properties (The system cannot find the file specified)
Build info: version: '4.34.0', revision: '707dcb4246*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: driver.version: unknown]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.InvalidArgumentException: Data is Wrong.\src\main\resources\TestData\CommanData.properties (The system cannot find the file specified)
Build info: version: '4.34.0', revision: '707dcb4246*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: driver.version: unknown
at com.Ecommerce.genericUtility.FileUtility.retriveDataFromProperty(FileUtility.java:16)
at com.Ecommerce.genericUtility.BaseTest.setUp(BaseTest.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.InvalidArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="register(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.Ecommerce.Register.RegisterTest@55fe41ea]" started-at="2025-08-22T16:08:12 IST" name="register" data-provider="TestData" finished-at="2025-08-22T16:08:12 IST" duration-ms="0" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.Error: Unresolved compilation problems: 
EXCEL_PATH cannot be resolved to a variable
REG_SHEET cannot be resolved to a variable
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.Error: Unresolved compilation problems: 
EXCEL_PATH cannot be resolved to a variable
REG_SHEET cannot be resolved to a variable

at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:58)
at org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:159)
at org.testng.internal.Parameters.handleParameters(Parameters.java:809)
at org.testng.internal.Parameters.handleParameters(Parameters.java:734)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:949)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.Error: Unresolved compilation problems: 
EXCEL_PATH cannot be resolved to a variable
REG_SHEET cannot be resolved to a variable

at com.Ecommerce.Register.RegisterTest.getRegisterData(RegisterTest.java:18)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:54)
... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method is-config="true" signature="toCloseDb()[pri:0, instance:com.Ecommerce.Register.RegisterTest@55fe41ea]" started-at="2025-08-22T16:08:12 IST" name="toCloseDb" finished-at="2025-08-22T16:08:12 IST" duration-ms="2" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[==Database closed successfully==]]>
            </line>
          </reporter-output>
        </test-method> <!-- toCloseDb -->
        <test-method is-config="true" signature="toCloseServer()[pri:0, instance:com.Ecommerce.Register.RegisterTest@55fe41ea]" started-at="2025-08-22T16:08:12 IST" name="toCloseServer" finished-at="2025-08-22T16:08:12 IST" duration-ms="2" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[==server closed successfully==]]>
            </line>
          </reporter-output>
        </test-method> <!-- toCloseServer -->
      </class> <!-- com.Ecommerce.Register.RegisterTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
